'use strict';

const chalk = require('chalk');
const { getDb } = require('../db');
const { initSchema } = require('../setup');
const { getPlugin } = require('../pluginLoader');
const git = require('../git');
const { releaseLocksForIssue } = require('../locks');

/**
 * Approve a fix: push branch, create PR, check CI, update status.
 */
async function approveCommand(source, id) {
  const plugin = getPlugin(source);
  const db = getDb();
  initSchema();

  const issue = db.prepare('SELECT * FROM issues WHERE id = ? AND source = ?').get(id, source);
  if (!issue) {
    console.error(chalk.red(`Issue ${id} not found for source ${source}.`));
    process.exit(1);
  }

  if (!['ai_fixed', 'verified'].includes(issue.status)) {
    console.error(chalk.red(`Issue ${id} is not ready for approval (status: ${issue.status}).`));
    console.error(chalk.gray(`Must be 'ai_fixed' or 'verified'.`));
    process.exit(1);
  }

  const now = new Date().toISOString();

  // Generate PR title and body
  const prTitle = generatePRTitle(issue);
  const prBody = generatePRBody(issue, db);

  console.log(chalk.cyan(`Pushing and creating PR for ${id}...`));

  let prUrl;
  try {
    prUrl = git.pushAndCreatePR(id, prTitle, prBody);
  } catch (err) {
    console.error(chalk.red(`Failed to create PR: ${err.message}`));
    process.exit(1);
  }

  console.log(chalk.green(`PR created: ${prUrl}`));

  // Store PR URL
  db.prepare('UPDATE issues SET fix_pr_url = ?, updated_at = ? WHERE id = ?')
    .run(prUrl, now, id);

  // CI check
  const ciWait = process.env.CI_WAIT !== 'false';
  if (ciWait) {
    console.log(chalk.gray('Waiting for CI checks...'));
    const ciResult = git.checkCIStatus(prUrl);

    if (!ciResult.passed) {
      console.error(chalk.red('CI checks failed. Auto-rejecting.'));
      console.error(chalk.gray(ciResult.details));

      // Log failed attempt
      logFixAttempt(db, id, 'failed', `CI failure: ${ciResult.details}`, now);

      // Set status to rejected
      db.prepare(
        `UPDATE issues SET status = 'rejected', rejected_reason = ?, updated_at = ? WHERE id = ?`
      ).run(`CI failure: ${ciResult.details.slice(0, 500)}`, now, id);

      releaseLocksForIssue(id);
      return;
    }

    console.log(chalk.green('CI checks passed.'));
  }

  // Update status to verified
  db.prepare(
    `UPDATE issues SET status = 'verified', reviewed_by = 'manual', updated_at = ? WHERE id = ?`
  ).run(now, id);

  // Log successful fix attempt
  let diffContent = '';
  try {
    diffContent = git.getDiffContent(issue.fix_branch);
  } catch (_) {}

  logFixAttempt(db, id, 'success', null, now, diffContent);

  // Release file locks
  releaseLocksForIssue(id);

  // Check if this fix resolves duplicate issues
  closeDuplicates(db, issue, now);

  console.log(chalk.green(`\n${id} approved and verified.`));
  if (prUrl) console.log(chalk.gray(`PR: ${prUrl}`));
}

function generatePRTitle(issue) {
  const prefix = issue.category === 'secret' ? 'fix(security)' :
    issue.category === 'vulnerability' ? 'fix(security)' :
    issue.category === 'bug' ? 'fix' :
    issue.source === 'aqa' ? 'fix(a11y)' :
    'fix';
  const desc = (issue.description || issue.rule_id || 'issue').slice(0, 60);
  return `${prefix}: ${desc} [${issue.id}]`;
}

function generatePRBody(issue, db) {
  const lines = [
    `## autofix-hub: ${issue.id}`,
    '',
    `**Source:** ${issue.source}`,
    `**Severity:** ${issue.severity}`,
    `**Category:** ${issue.category || 'N/A'}`,
    `**Rule:** ${issue.rule_id || 'N/A'}`,
    `**File:** ${issue.file_path || 'N/A'}${issue.line_number ? `:${issue.line_number}` : ''}`,
    `**Impact Score:** ${issue.impact_score || 'N/A'}`,
    `**Effort:** ${issue.estimated_effort || 'N/A'}`,
    `**Review Level:** ${issue.review_level || 'N/A'}`,
    '',
    '### Description',
    issue.description || 'No description.',
    '',
  ];

  // Cluster info
  if (issue.cluster_id) {
    const clusterIssues = db.prepare(
      `SELECT id, file_path, description FROM issues WHERE cluster_id = ? AND id != ?`
    ).all(issue.cluster_id, issue.id);

    if (clusterIssues.length > 0) {
      lines.push('### Related Issues (Cluster)');
      for (const ci of clusterIssues) {
        lines.push(`- ${ci.id}: ${ci.file_path || ''} — ${(ci.description || '').slice(0, 80)}`);
      }
      lines.push('');
    }
  }

  // Fix prompt used
  if (issue.fix_prompt) {
    lines.push('<details><summary>Fix Prompt Used</summary>', '', '```', issue.fix_prompt, '```', '', '</details>', '');
  }

  lines.push('---', '*Generated by autofix-hub*');
  return lines.join('\n');
}

function logFixAttempt(db, issueId, status, errorLog, timestamp, diffContent) {
  const attemptNum = (db.prepare(
    'SELECT MAX(attempt_number) as max_num FROM fix_attempts WHERE issue_id = ?'
  ).get(issueId).max_num || 0) + 1;

  db.prepare(`
    INSERT INTO fix_attempts (issue_id, attempt_number, status, diff_content, error_log, attempted_at)
    VALUES (?, ?, ?, ?, ?, ?)
  `).run(issueId, attemptNum, status, diffContent || null, errorLog || null, timestamp);
}

function closeDuplicates(db, issue, now) {
  if (!issue.dedup_group) return;

  const duplicates = db.prepare(`
    SELECT id FROM issues
    WHERE dedup_group = ? AND is_duplicate = 1 AND status = 'open' AND id != ?
  `).all(issue.dedup_group, issue.id);

  if (duplicates.length === 0) return;

  const closeStmt = db.prepare(
    `UPDATE issues SET status = 'closed', resolved_at = ?, updated_at = ?, reviewed_by = 'auto-dedup' WHERE id = ?`
  );

  for (const dup of duplicates) {
    closeStmt.run(now, now, dup.id);
  }

  if (duplicates.length > 0) {
    console.log(chalk.gray(`  Auto-closed ${duplicates.length} duplicate issue(s).`));
  }
}

module.exports = { approveCommand };
