'use strict';

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const { getDb } = require('../db');
const { initSchema } = require('../setup');
const { loadAutomationConfig, isBlocklisted } = require('../automationConfig');
const { getClub, getClubIssues } = require('../clubbing');
const { getPlugin } = require('../pluginLoader');

function runIn(cwd, cmd, opts = {}) {
  return execSync(cmd, { cwd, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], ...opts }).trim();
}

function runInSafe(cwd, cmd, opts = {}) {
  try { return { ok: true, output: runIn(cwd, cmd, opts) }; }
  catch (err) { return { ok: false, output: (err.stderr && err.stderr.toString()) || err.message }; }
}

function changedFiles(cwd) {
  const out = runInSafe(cwd, 'git status --porcelain').output || '';
  return out.split('\n').map(l => l.trim()).filter(Boolean).map(l => l.replace(/^..\s*/, '').replace(/.*->\s*/, ''));
}

function buildPRTitle(club, issueCount) {
  const { category, rule_id } = club;
  const label = (rule_id && rule_id !== 'unknown') ? rule_id : category;
  const n = issueCount;
  return `autofix(${club.source}): ${label} — ${n} ${n === 1 ? 'issue' : 'issues'}`.slice(0, 120);
}

function buildPRBody(club, issues, plugin) {
  const lines = [
    `## autofix-hub: ${club.id}`,
    '',
    `**Source:** ${club.source}`,
    `**Category:** ${club.category}`,
    `**Rule:** ${club.rule_id}`,
    `**Issues:** ${issues.length}`,
    `**Files:** ${club.files_count}`,
    club.common_dir ? `**Common directory:** \`${club.common_dir}\`` : '',
    '',
    '### Issues fixed',
    '',
    '| # | ID | File | Line | Severity |',
    '|---|----|------|------|----------|',
  ].filter(Boolean);
  issues.forEach((i, idx) => {
    lines.push(`| ${idx + 1} | \`${i.id}\` | \`${i.file_path || '-'}\` | ${i.line_number || '-'} | ${i.severity || '-'} |`);
  });
  lines.push('', '---', '*Generated by autofix-hub — review each change and merge when satisfied.*');
  return lines.join('\n');
}

async function commitCommand(clubIdArg, opts = {}) {
  initSchema();
  const config = loadAutomationConfig();
  const db = getDb();

  const club = getClub(clubIdArg);
  if (!club) {
    console.log(JSON.stringify({ status: 'error', error: `Club ${clubIdArg} not found` }));
    process.exit(1);
  }

  const cwd = club.worktree_path;
  if (!cwd || !fs.existsSync(cwd)) {
    console.log(JSON.stringify({
      status: 'error', error: `Worktree missing for club ${club.id}. Run 'autofix-hub worktree create ${club.id}' first.`,
    }));
    process.exit(1);
  }

  // Blocklist enforcement on the actual diff.
  const diffFiles = changedFiles(cwd);
  if (diffFiles.length === 0) {
    console.log(JSON.stringify({
      status: 'error', error: 'No changes to commit — worktree is clean.',
    }));
    process.exit(1);
  }
  const blocked = diffFiles.filter(f => isBlocklisted(f, config.blocklist));
  if (blocked.length > 0) {
    console.log(JSON.stringify({
      status: 'refused',
      reason: 'blocklist',
      blocked_paths: blocked,
      hint: `Run 'autofix-hub abandon ${club.id} --reason "touched blocklist"'`,
    }, null, 2));
    process.exit(3);
  }

  const issues = getClubIssues(club.id);
  const plugin = getPlugin(club.source);

  const title = opts.title || buildPRTitle(club, issues.length);
  const body = opts.body || buildPRBody(club, issues, plugin);

  // Stage + commit
  runInSafe(cwd, 'git add -A');
  const commitMsg = `${title}\n\nClub: ${club.id}\nIssues: ${issues.map(i => i.id).join(', ')}`;
  const commit = spawnSync('git', ['commit', '-m', commitMsg], { cwd, encoding: 'utf8' });
  if (commit.status !== 0) {
    console.log(JSON.stringify({
      status: 'error', error: `git commit failed: ${(commit.stderr || '').slice(-2000)}`,
    }));
    process.exit(1);
  }

  // Push
  const push = runInSafe(cwd, `git push -u origin "${club.branch}"`);
  if (!push.ok) {
    console.log(JSON.stringify({ status: 'error', error: `git push failed: ${push.output}` }));
    process.exit(1);
  }

  // gh pr create
  const prArgs = ['pr', 'create', '--title', title, '--body', body, '--head', club.branch];
  if (opts.baseBranch || config.wip.base_branch) {
    prArgs.push('--base', opts.baseBranch || config.wip.base_branch);
  }
  if (config.pr.draft) prArgs.push('--draft');
  if (config.wip.label) prArgs.push('--label', config.wip.label);

  const gh = spawnSync('gh', prArgs, { cwd, encoding: 'utf8' });
  if (gh.status !== 0) {
    console.log(JSON.stringify({
      status: 'error', error: `gh pr create failed: ${(gh.stderr || gh.stdout || '').slice(-2000)}`,
    }));
    process.exit(1);
  }
  const prUrl = (gh.stdout || '').trim().split('\n').pop();

  const now = new Date().toISOString();
  db.prepare(`
    UPDATE clubs SET status = 'pr_opened', pr_url = ?, updated_at = ? WHERE id = ?
  `).run(prUrl, now, club.id);

  // Transition issues to ai_fixed + record PR url
  const updateIssue = db.prepare(`
    UPDATE issues SET status = 'ai_fixed', fix_branch = ?, fix_pr_url = ?, updated_at = ? WHERE id = ? AND status IN ('open','in_progress')
  `);
  const tx = db.transaction(() => {
    for (const i of issues) updateIssue.run(club.branch, prUrl, now, i.id);
  });
  tx();

  console.log(JSON.stringify({
    status: 'ok',
    club_id: club.id,
    pr_url: prUrl,
    branch: club.branch,
    issues_count: issues.length,
    files: diffFiles,
  }, null, 2));
}

module.exports = { commitCommand };
