'use strict';

const path = require('path');
const fs = require('fs');
const { spawnSync } = require('child_process');
const { getDb } = require('../db');
const { initSchema } = require('../setup');
const { getProjectRoot } = require('../config');

function fmtClubRow(c) {
  const statusIcon = {
    pr_opened: 'PR',
    abandoned: '✗',
    in_progress: '…',
    proposed: '·',
  }[c.status] || c.status;
  return `| ${statusIcon} | \`${c.id}\` | ${c.rule_id || c.category} | ${c.issue_count} | ${c.files_count} | ${c.pr_url || c.abandon_reason || '-'} |`;
}

function buildMarkdown(session, clubs) {
  const opened = clubs.filter(c => c.status === 'pr_opened');
  const abandoned = clubs.filter(c => c.status === 'abandoned');
  const inProgress = clubs.filter(c => c.status === 'in_progress');
  const proposed = clubs.filter(c => c.status === 'proposed');

  const totalIssuesFixed = opened.reduce((s, c) => s + (c.issue_count || 0), 0);

  const lines = [
    `# autofix-hub session ${session.id}`,
    '',
    `- **Source:** ${session.source}`,
    `- **Started:** ${session.started_at}`,
    `- **Ended:** ${session.ended_at || '(active)'}`,
    `- **PRs opened:** ${opened.length}`,
    `- **Clubs abandoned:** ${abandoned.length}`,
    `- **Issues fixed:** ${totalIssuesFixed}`,
    '',
    '## Clubs',
    '',
    '| Status | ID | Rule | Issues | Files | PR / Reason |',
    '|--------|----|------|--------|-------|-------------|',
  ];
  for (const c of [...opened, ...inProgress, ...abandoned, ...proposed]) {
    lines.push(fmtClubRow(c));
  }
  lines.push('');

  if (opened.length > 0) {
    lines.push('## Pull requests', '');
    for (const c of opened) {
      lines.push(`- [${c.rule_id || c.category} (${c.issue_count})](${c.pr_url})`);
    }
    lines.push('');
  }
  if (abandoned.length > 0) {
    lines.push('## Abandoned clubs', '');
    for (const c of abandoned) {
      lines.push(`- \`${c.id}\` — ${c.rule_id || c.category}: ${c.abandon_reason || 'no reason'}`);
    }
    lines.push('');
  }

  lines.push('---', '*Generated by autofix-hub*');
  return lines.join('\n');
}

async function summarizeCommand(opts = {}) {
  initSchema();
  const db = getDb();

  const sessionId = opts.session;
  let session;
  if (sessionId) {
    session = db.prepare('SELECT * FROM sessions WHERE id = ?').get(sessionId);
  } else {
    session = db.prepare("SELECT * FROM sessions WHERE status = 'active' ORDER BY started_at DESC LIMIT 1").get();
  }
  if (!session) {
    console.log(JSON.stringify({ status: 'error', error: `Session not found: ${sessionId || '(no active session)'}` }));
    process.exit(1);
  }

  const clubs = db.prepare('SELECT * FROM clubs WHERE session_id = ? ORDER BY updated_at ASC').all(session.id);

  // Mark session ended if caller asked
  if (opts.end && !session.ended_at) {
    const now = new Date().toISOString();
    db.prepare("UPDATE sessions SET ended_at = ?, status = 'ended' WHERE id = ?").run(now, session.id);
    session.ended_at = now;
  }

  const md = buildMarkdown(session, clubs);

  const outDir = path.join(getProjectRoot(), '.autofix-hub', 'sessions', session.id);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const mdPath = path.join(outDir, 'summary.md');
  fs.writeFileSync(mdPath, md, 'utf8');

  let postedIssueUrl = null;
  if (opts.post === 'github-issue') {
    const title = `autofix session ${session.id}: ${clubs.filter(c => c.status === 'pr_opened').length} PRs`;
    const r = spawnSync('gh', ['issue', 'create', '--title', title, '--body', md], { encoding: 'utf8' });
    if (r.status === 0) postedIssueUrl = (r.stdout || '').trim().split('\n').pop();
  }

  console.log(JSON.stringify({
    status: 'ok',
    session_id: session.id,
    source: session.source,
    summary_path: mdPath,
    posted_issue_url: postedIssueUrl,
    totals: {
      prs_opened: clubs.filter(c => c.status === 'pr_opened').length,
      abandoned: clubs.filter(c => c.status === 'abandoned').length,
      in_progress: clubs.filter(c => c.status === 'in_progress').length,
      proposed: clubs.filter(c => c.status === 'proposed').length,
      issues_fixed: clubs.filter(c => c.status === 'pr_opened').reduce((s, c) => s + (c.issue_count || 0), 0),
    },
    clubs: clubs.map(c => ({
      id: c.id, status: c.status, rule_id: c.rule_id, category: c.category,
      issue_count: c.issue_count, pr_url: c.pr_url, abandon_reason: c.abandon_reason,
    })),
  }, null, 2));
}

module.exports = { summarizeCommand };
